bash simplify_script.sh commons-cli commons-cli
bash simplify_script.sh commons-codec commons-codec
bash simplify_script.sh commons-csv commons-csv
bash simplify_script.sh commons-validator commons-validator
bash simplify_script.sh commons-fileupload commons-fileupload
bash simplify_script.sh commons-pool commons-pool
bash simplify_script.sh commons-graph commons-graph
bash simplify_script.sh commons-exec commons-exec
bash simplify_script.sh jansi jansi
bash simplify_script.sh JavaFastPFOR JavaFastPFOR
